#[cfg(feature="mlua")]
pub mod typed;
#[cfg(feature="mlua")]
pub mod extras;

#[cfg(feature="mlua")]
pub use mlua;

#[cfg(feature="derive")]
pub use mlua_extras_derive::{Typed, UserData, TypedUserData, typed_user_data_impl};

// These hidden traits provide empty default implementations of __auto_add_fields
// and __auto_add_methods for all types via blanket impls. The TypedUserData derive
// generates `impl TypedUserData` that calls `Self::__auto_add_fields(fields)` and
// `Self::__auto_add_methods(methods)`. Rust's method resolution means that when
// an inherent method with the same name exists (generated by the derive for fields,
// or by #[mlua_extras::typed_user_data_impl] for methods), it shadows the trait default.
// When no inherent method exists, the call falls through to the empty trait default
// here.
// In other words: this allows the derive on the struct and the typed_user_data_impl macro
// independently optional without requiring the user to think about explicitly
// indicating that they have fields and methods or just fields.
#[cfg(feature = "derive")]
#[doc(hidden)]
pub trait __DefaultAutoFields: Sized {
    fn __auto_add_fields<F>(_f: &mut F) {}
}
#[cfg(feature = "derive")]
impl<T: Sized> __DefaultAutoFields for T {}

#[cfg(feature = "derive")]
#[doc(hidden)]
pub trait __DefaultAutoMethods: Sized {
    fn __auto_add_methods<M>(_m: &mut M) {}
}
#[cfg(feature = "derive")]
impl<T: Sized> __DefaultAutoMethods for T {}

#[cfg(feature = "send")]
/// Used by the `send` feature
pub trait MaybeSend: Send {}
#[cfg(feature = "send")]
impl<T: Send> MaybeSend for T {}

#[cfg(not(feature = "send"))]
/// Used by the `send` feature
pub trait MaybeSend {}
#[cfg(not(feature = "send"))]
impl<T> MaybeSend for T {}
